name: Feature to Dev CI

on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Récupère toutes les branches, pas seulement la branche active

    - name: Install dependencies for backend
      run: |
        cd backend
        npm install

    - name: Run backend unit tests
      run: |
        cd backend
        npm test

    - name: Install dependencies for frontend
      run: |
        cd frontend
        npm install

    - name: Run frontend unit tests
      run: |
        cd frontend
        npm test

    - name: Merge dev to main
      if: success()
      uses: devmasx/merge-branch@v1.3.0
      with:
        target_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger push to main
      if: success()
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git commit --allow-empty -m "Trigger dev-to-main workflow"
        git push origin main
